"""Local artificial-satellite state and resource domain."""

from .crossing_oracle import (
    LocalSatelliteCrossingOracle,
    LocalSatelliteCrossingQuery,
    SatelliteCrossingConvergenceError,
)
from .crossing_acceleration import (
    AcceleratedCrossingEvidence,
    AcceleratedCrossingPolicy,
    AcceleratedLocalSatelliteCrossingOracle,
    ConeShellDecision,
    ConeShellPolicy,
    ConeShellSelection,
    ConservativeConeShellSelector,
)
from .crossing_batch import (
    FieldAirmassAdmission,
    FieldAirmassCertifier,
    MultiFieldCrossingPolicy,
    MultiFieldCrossingRequest,
    MultiFieldCrossingResult,
    MultiFieldCrossingValidationError,
    MultiFieldSatelliteCrossingCoordinator,
    MultiFieldValidationFailure,
)
from .crossing_matrix import (
    CROSSING_MATRIX_IMPLEMENTATION,
    MATRIX_DOCUMENT_KIND,
    MATRIX_ISOLATION_IDENTITY,
    CrossingMatrixPolicy,
    MatrixEquivalenceError,
    MatrixResourceObservation,
    MatrixRouteRun,
    MatrixSpecimenIdentity,
    run_equivalence_matrix,
)
from .exact_tracks import (
    EXACT_LOCAL_TRACK_IMPLEMENTATION,
    EXACT_LOCAL_TRACK_PRODUCT,
    EXACT_LOCAL_TRACK_SCHEMA_VERSION,
    EXACT_LOCAL_TRACK_STATUS,
    ExactLocalSatelliteTrack,
    ExactLocalSatelliteTrackRealizer,
    ExactLocalSatelliteTrackSample,
    ExactLocalTrackError,
    ExactLocalTrackEvaluation,
    ExactLocalTrackPolicy,
)
from .elements import SatelliteElementRecord
from .snapshot_admission import (
    CELESTRAK_ACTIVE_20260917_IDENTITY,
    CELESTRAK_ACTIVE_20260917_POLICY_IDENTITY,
    ExternalSnapshotAdmission,
    ExternalSnapshotAdmissionPolicy,
    ExternalSnapshotIdentity,
    SNAPSHOT_ADMISSION_IMPLEMENTATION,
)
from .snapshot_evidence import (
    MEDIUM_SPECIMEN_DOCUMENT_KIND,
    MEDIUM_SPECIMEN_IMPLEMENTATION,
    REPRESENTATIVES_PER_BIN,
    select_medium_snapshot,
)
from .sgp4 import (
    SatellitePropagationError,
    SatelliteTemeState,
    Sgp4TemePropagator,
    split_julian_date,
)
from .snapshots import (
    DEFAULT_SNAPSHOT_ID,
    SatelliteElementSnapshot,
    SatelliteSnapshotManifest,
    load_snapshot,
    load_snapshot_directory,
)
from .topocentric import (
    SatelliteFieldCenterAltitudeEvaluator,
    SatelliteEarthOrientationError,
    SatelliteEarthOrientationEvidence,
    SatelliteTopocentricState,
    SatelliteTopocentricTransformer,
)

__all__ = [
    "AcceleratedCrossingEvidence",
    "AcceleratedCrossingPolicy",
    "AcceleratedLocalSatelliteCrossingOracle",
    "ConeShellDecision",
    "ConeShellPolicy",
    "ConeShellSelection",
    "CROSSING_MATRIX_IMPLEMENTATION",
    "MATRIX_DOCUMENT_KIND",
    "MATRIX_ISOLATION_IDENTITY",
    "CrossingMatrixPolicy",
    "MatrixEquivalenceError",
    "MatrixResourceObservation",
    "MatrixRouteRun",
    "MatrixSpecimenIdentity",
    "ConservativeConeShellSelector",
    "EXACT_LOCAL_TRACK_IMPLEMENTATION",
    "EXACT_LOCAL_TRACK_PRODUCT",
    "EXACT_LOCAL_TRACK_SCHEMA_VERSION",
    "EXACT_LOCAL_TRACK_STATUS",
    "ExactLocalSatelliteTrack",
    "ExactLocalSatelliteTrackRealizer",
    "ExactLocalSatelliteTrackSample",
    "ExactLocalTrackError",
    "ExactLocalTrackEvaluation",
    "ExactLocalTrackPolicy",
    "ExternalSnapshotAdmission",
    "ExternalSnapshotAdmissionPolicy",
    "ExternalSnapshotIdentity",
    "FieldAirmassAdmission",
    "FieldAirmassCertifier",
    "CELESTRAK_ACTIVE_20260917_IDENTITY",
    "CELESTRAK_ACTIVE_20260917_POLICY_IDENTITY",
    "DEFAULT_SNAPSHOT_ID",
    "LocalSatelliteCrossingOracle",
    "LocalSatelliteCrossingQuery",
    "MEDIUM_SPECIMEN_DOCUMENT_KIND",
    "MEDIUM_SPECIMEN_IMPLEMENTATION",
    "MultiFieldCrossingPolicy",
    "MultiFieldCrossingRequest",
    "MultiFieldCrossingResult",
    "MultiFieldCrossingValidationError",
    "MultiFieldSatelliteCrossingCoordinator",
    "MultiFieldValidationFailure",
    "REPRESENTATIVES_PER_BIN",
    "SatelliteCrossingConvergenceError",
    "SatelliteEarthOrientationError",
    "SatelliteEarthOrientationEvidence",
    "SatelliteFieldCenterAltitudeEvaluator",
    "SatelliteElementRecord",
    "SatelliteElementSnapshot",
    "SatelliteSnapshotManifest",
    "SatellitePropagationError",
    "SNAPSHOT_ADMISSION_IMPLEMENTATION",
    "SatelliteTemeState",
    "SatelliteTopocentricState",
    "SatelliteTopocentricTransformer",
    "Sgp4TemePropagator",
    "split_julian_date",
    "load_snapshot",
    "load_snapshot_directory",
    "run_equivalence_matrix",
    "select_medium_snapshot",
]
