"""Backward-compatible numeric names for Wenu paint roles."""

from wenu.rendering import paint_roles as roles


BACKGROUND = roles.BACKGROUND.zorder
MILKY_WAY = roles.MILKY_WAY.zorder
MAGELLANIC_CLOUDS = roles.MAGELLANIC_CLOUDS.zorder
GALAXY_FILLS = roles.GALAXY_FILLS.zorder
BOUNDARIES = roles.BOUNDARIES.zorder
CURVES = roles.CURVES.zorder
CONSTELLATIONS = roles.CONSTELLATIONS.zorder
GALAXIES = roles.GALAXIES.zorder
SUPERNOVA_REMNANTS = roles.SUPERNOVA_REMNANTS.zorder
PLANETARY_NEBULAE = roles.PLANETARY_NEBULAE.zorder
OPEN_CLUSTERS = roles.OPEN_CLUSTERS.zorder
GLOBULAR_CLUSTERS = roles.GLOBULAR_CLUSTERS.zorder
STARS = roles.STARS.zorder
BRIGHT_STARS = roles.BRIGHT_STARS.zorder
MULTIPLE_STARS = roles.MULTIPLE_STARS.zorder
VARIABLE_STARS = roles.VARIABLE_STARS.zorder
POINTS = roles.POINTS.zorder
LABELS = roles.LABELS.zorder
GALAXY_LABELS = LABELS
SUPERNOVA_REMNANT_LABELS = LABELS
PLANETARY_NEBULA_LABELS = LABELS
GLOBULAR_CLUSTER_LABELS = LABELS
OPEN_CLUSTER_LABELS = LABELS
